
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - identityconfig.identitatem.io
  resources:
  - strategies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identityconfig.identitatem.io
  resources:
  - strategies/finalizers
  verbs:
  - update
- apiGroups:
  - identityconfig.identitatem.io
  resources:
  - strategies/status
  verbs:
  - get
  - patch
  - update
