# permissions for end users to view strategies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strategy-viewer-role
rules:
- apiGroups:
  - identitatem.io
  resources:
  - strategies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identitatem.io
  resources:
  - strategies/status
  verbs:
  - get
